### ISSUE TITLE
"bits/stdc++.h" missing 

### ISSUE THREAD

**Issue by MarkMa1990** [deerishi/tsp-using-simulated-annealing-c-#2]
Thanks for your sharing. It seems the file "bits/stdc++.h" is missing. So compiling is not possible.

**Comment by deerishi** [comment]
That is a standard header file that should be already present with gcc. https://www.quora.com/What-is-the-file-bits-stdc++-h?share=1

You might wanna update your gcc compiler

**Comment by MarkMa1990** [comment]
Hi, thanks for your reminding. It was my windows VS problem. Now I turn to Ubuntu, it is working. # g++ tsp.cpp -o tsp --std=c++11. I would close this issue. Thanks again.
